# Generated by Django 3.1.1 on 2020-09-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fitness_Status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthtube',
            old_name='Category',
            new_name='category',
        ),
    ]
